---
title: "Teletrabajo y Salud Mental"
author: "Paula Quirós, Carlota García y Alma Caneiro"
date: "`r Sys.Date()`"
output: 
  html_document:
      toc: true
      toc_float: true 
--- 
<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Introducción

La relación entre la salud mental y el empleo, especialmente en los trabajos que nos llevan a pasar muchas horas frente a un ordenador, ha cobrado una importancia creciente en los últimos años debido al aumento de casos de ansiedad, episodios depresivos y estrés laboral, así como otro tipo de enfermedades mentales entre los profesionales de los diferentes sectores. Nuestro seminario aborda este vínculo.

Buscamos analizar cómo el aislamiento social, la falta de contacto humano, la monotonía y la dificultad para separar la vida laboral de la personal contribuyen a deteriorar el bienestar emocional de las personas que trabajan en espacios confinados. Además, queremos comprender por qué estos factores pueden desencadenar problemas como ansiedad, estrés, depresión y trastornos del sueño, y cómo el entorno laboral puede influir en la aparición y agravamiento de estos síntomas.


#  Objetivos

## Objetivo General
Demostrar si es que existe, la relación entre episodios depresivos y el teletrabajo, en la actualidad. 


## Objetivos Específicos

1. Analizar la relación entre la modalidad de teletrabajo y el estado de salud mental de los trabajadores residentes en cada comunidad autónoma.

2. Cuanto mayor es el peso del turismo y sectores presenciales en la economía local para cada provincia de las Islas Canarias , menor es la proporción de trabajadores que pueden tele trabajar y así podremos asociarlo con nuestra idea principal (la salud mental) 

3.

# 3. Metodología y Resultados

Esta es la sección principal. Aquí es donde pondréis los siguientes *chunks* de R para cargar, limpiar y analizar vuestros datos.